### PR TITLE
Switch to lerna

### PR DESCRIPTION
**Pull request by silkentrance**
also fixes

- #157
- #114

### CODE REVIEW

**Comment by pana-cc** [comment]
I approve the idea in general, but I kind of can not compare the 140 files right now.

**Comment by silkentrance** [comment]
@pana-cc let's see how this works out. In my opinion this is the only way to go for and existing tests, on my behalf, showed, that the integration with karma and also webpack, can only be achieved this way, unless one wanted to create multiple repositories...

**Comment by silkentrance** [comment]
But, alas, we still have to work on the documentation for this, to show that we now support the browser, i.e. karma and so on.

**Comment by silkentrance** [comment]
integrating current master

**Pull request merged**
