### PR TITLE
Add testdeck/jest to the mix

### PR DESCRIPTION
**Pull request by silkentrance**
Also addresses #174, but I figure, with an npm scope, this is rather obsolete.

### CODE REVIEW

**Comment by silkentrance** [comment]
please note that with jest/jasmine in the mix, we cannot use the hoisting feature of lerna anymore, since the embedded expect interface breaks with the karma code that is using expectjs.

**Comment by pana-cc** [comment]
I just pushed one commit moving the packages in the `@testdeck` scope and set versions to 0.0.1.
I will try to extract a common package now.

**Comment by silkentrance** [comment]
👍 0.0.1... this will be a long way to 1.0.0 😄

**Comment by pana-cc** [comment]
:) but it looks good for now, in branch `gh-163-core` you can check the progress... hopefully most of the code will be in that single core, and the mocha, jest, jasmine will be just boilerplate

**Comment by silkentrance** [comment]
Merging now. We can do the documentation part and additional details, i.e. slow decorator/trait not supported, skipOnError trait not supported, later.

**Pull request merged**
