### PR TITLE
Add a 'context' symbol and expose mocha context

### PR DESCRIPTION
**Pull request by pana-cc**
Don't merge yet!

There are tests added to the core, and the `this` seems to be passed down to test methods properly.
I have to just add typing's for mocha/jest/etc. and eventually add a test or two there as well.

### CODE REVIEW

**Comment by panayot-cankov** [comment]
Build started
git clone -q --branch=pana-cc/context https://github.com/testdeck/testdeck.git C:\projects\testdeck
fatal: unable to access 'https://github.com/testdeck/testdeck.git/': Could not resolve host: github.com
Command exited with code 128

Nice build fail :) It should be fine

**Comment by pana-cc** [comment]
Ok,
This looks ready for a review. It somewhat works on my machine but keeps failing on the CI.
@silkentrance would you like to review the squashed version?

**Comment by panayot-cankov** [comment]
ok I broke it here as well, `git clean -xdf` `git reset --hard` broke and then the jasmine tests fail...

**Comment by pana-cc** [comment]
Ok, I think latest jest versions do not execute hooks in a reverse order.
I set the executeAfterHooksInReverseOrder to the default of false for jest.

P.S. panayot-cankov is my work related account

**Comment by pana-cc** [comment]
NYC coverage fails, throws on node 10 and outputs “Unknown%” coverage on the newer versions.

**Comment by pana-cc** [comment]
I disabled nyc, something is wrong with it, but we have pretty neat coverage at the moment, and I don't have the time to dig down what happened to it. Congratulations, we have a new feature - context. At this point I don't think it is a breakign change. it would have if it were in mocha-typescript, but since testdeck is new set of packages, it is something that was never available in testdeck. And migration is quite straight forward, instead of `@context myField`, you just use `this[context]` in methods.

**Comment by KsenyLa** [comment]
It has been almost one year since issue was created and we still hope for the solution. Could you publish it please?

**Pull request merged**
