### PR TITLE
test for context

### PR DESCRIPTION
**Pull request by dcharbonnier**

### CODE REVIEW

**Comment by silkentrance** [comment]
@dcharbonnier Might I ask what these assertions in the before/after hooks are for? We only record the fact that these have been called...

**Comment by dcharbonnier** [comment]
For me those tests should pass and if not it means there is a bug no?

**Comment by silkentrance** [comment]
@dcharbonnier Well, no. First, one should not implement any assertions in before/after hooks as these will not be recorded as tests but will just make the test suite fail. Second, there are no such interfaces such as Suite or CallbacksSuite.

Closing as invalid.

**Comment by silkentrance** [comment]
As for recursion, you might get a bang out of this flick: https://www.google.com/search?q=movie+synchronicity&oq=movie+synchroni&aqs=chrome.0.0j46j0j69i57j0l4.5679j0j7&sourceid=chrome&ie=UTF-8

**Comment by dcharbonnier** [comment]
The problem here is that it looks like the context is lost, I think but I may be wrong that on a before and an after you should have in instance and it's not the case. For me this makes before and after useless. And this is working for mocha

**Comment by dcharbonnier** [comment]
I can confirm mocha is working jest is no : 
```

diff --git a/packages/jest/test.ts b/packages/jest/test.ts
index dd07f42..8d56eab 100644
--- a/packages/jest/test.ts
+++ b/packages/jest/test.ts
@@ -11,6 +11,7 @@ describe("tests", function() {
         }
 
         public before() {
+            assert.instanceOf(this, Suite);
             events.push("Suite before");
         }
 
@@ -28,6 +29,7 @@ describe("tests", function() {
         }
 
         public after() {
+            assert.instanceOf(this, Suite);
             events.push("Suite after");
         }
 
diff --git a/packages/mocha/test.ts b/packages/mocha/test.ts
index dd57c81..d5b5307 100644
--- a/packages/mocha/test.ts
+++ b/packages/mocha/test.ts
@@ -11,6 +11,7 @@ describe("tests", function() {
         }
 
         public before() {
+            assert.instanceOf(this, Suite);
             events.push("Suite before");
         }
 
@@ -28,6 +29,7 @@ describe("tests", function() {
         }
 
         public after() {
+            assert.instanceOf(this, Suite);
             events.push("Suite after");
         }
 
```

**Comment by silkentrance** [comment]
@dcharbonnier I will test this with a jest based test suite I am currently working on.

**Comment by silkentrance** [comment]
@dcharbonnier I can confirm this behaviour when using jest.

**Comment by silkentrance** [comment]
When using testdeck jest then this will be null in the after hook.

**Comment by silkentrance** [comment]
@dcharbonnier Well, who would have guessed it. Jest will call the afterEach hooks in the reverse order that they had been added. Nice. Now, how to fix that.

**Comment by silkentrance** [comment]
@dcharbonnier can you please file a bug report against `@testdeck/jest` for this, if not, I will create one myself?

**Pull request closed without merging**
