### PR TITLE
feature #208: refactor watcher to separate package

### PR DESCRIPTION
**Pull request by silkentrance**
**WIP**

- needs additional work: jasmine/jest options
- needs additional integration tests: jasmine/jest
- made private for now until above issues have been resolved

### CODE REVIEW

**Comment by pana-cc** [comment]
Awesome, the watcher is utility that can be used without the decorators interface and certainly we can make it work with any test runner.

**Comment by silkentrance** [comment]
> Awesome, the watcher is utility that can be used without the decorators interface and certainly we can make it work with any test runner.

Don't know about 'making it work with any test runner' since for example jest brings its own. And there are certainly others, such as gulp-watch and so on. Also, karma does watch the filesystem for changes and recompiles everything...

**Comment by pana-cc** [comment]
Then maybe it outlived its usefulness. But back in the time when it was written most watchers used something like node ts, that will simply transpile the code and rerun tests. That was missing the project settings and potential type errors. Angular wanted to use typescript and webpack, and went down to approach similar to the watcher here, they replaced the webpack filesystem with something that comes from typescript and knows for which ts files what js files will be generated... I am sure things are better now. If we can drop the watcher if karma can replace it, but isn't karma running tests in browsers? The watcher here was supposed to support TDD by letting you focus tests and iterate quickly, karma's purpose is different.

**Comment by pana-cc** [comment]
The watcher is tied to mocha, I was thinking to make it use tsc with watch, and when it is successful run something like `npm test` or `npm unit-test`, and delete the mocha related code from it.

**Comment by silkentrance** [comment]
Yeah, of course it is still useful, but not in all cases, so I would not drop it.

I currently have stopped working on this due to some private issues and also that I am currently working on something altogether different.

I will continue with this in a few weeks from now.

**Comment by silkentrance** [comment]
I still got no time to pursue this further. Will try in the next week or so.

**Comment by silkentrance** [comment]
Putting this on halt for now as it is not an important feature to have.
Will reopen as soon as I find the time.

**Pull request closed without merging**
