### PR TITLE
V1 Logo

### PR DESCRIPTION
**Pull request by pana-cc**

### CODE REVIEW

**Comment by silkentrance** [comment]
I love the logo. Great!

**Comment by silkentrance** [comment]
Which font are you using? Is it royalty free?

**Comment by pana-cc** [comment]
Diavlo Bold, I was looking for free fonts when I got it but I’ll have to doublecheck that. It is available here for example: https://www.fontsquirrel.com/fonts/diavlo but I think I obtained it from another site.

**Comment by silkentrance** [comment]
Quoting from the license

```
Font license information

• This font is free for personal and commercial use 
• This font file may not be modified 
• This font file may not be distributed -not online nor on any media- without my permission 
• Embedding (in PDF’s, Flash files and programs) is allowed  
• This font may not be sold 
• This font is the intellecual property of Jos Buivenga
 • Exljbris (Jos Buivenga) is not liable for any damage resulting from the use of this font
```

it seems that we have a big problem if it causes any damage while reading it... :grin:

**Comment by pana-cc** [comment]
@silkentrance I will attache SVGs for the logo. The square version with the big red @ will stand out on dark backgrounds, I will check what colors for the text of the full `@testdeck()` one will be suitable for dark background.

**Comment by pana-cc** [comment]
Added SVGs.

**Pull request merged**
